### ISSUE TITLE
<mx-tag>来处理重复的代码片段及magix-gallery组件

### ISSUE THREAD

**Issue by xinglie** [thx/magix-combine#19]
当我们在处理html时，通常会遇到重复的，又稍微复杂的html片段，我们以一个loading为例

```html
<div mx-view="app/views/list">
    <div class="loading">
        <span></span>
        <span></span>
        <span></span>
    </div>
</div>
```

比如我们用css3写3个圆点不断变换的动画。当项目中需要很多地方用这个loading动画时，我们需要把它复制粘贴到需要用到的地方。

如果后期视觉设计师对这个loading动画不满足，要换一种，万一要动html结构，那我们前端工程师就有得忙了。

magix-combine针对这个问题，有一个解决方案，如下：在html中定义<mx-tag>标签，然后在magix-combine工具的配置中，统一处理。

```html
<div mx-view="app/views/list">
    <mx-loading />
</div>
```

使用mx-开头的标签来定义一个magix-combine要识别处理的自定义标签

然后我们在magix-combine的配置里来处理这个自定义的标签

```js
var combineTool = require('magix-combine');

combineTool.config({
    loaderType:'cmd', //or amd
    mxTagProcessor:function(tagInfo){
         if(tagInfo.tag=='loading'){//获取标签名字，去掉mx-后的名字
            return '<div class="loading"><span></span><span></span><span></span></div>';
         }
        return '';//如果不能识别，则返回空字符串，删除掉这个标签
    }
});
```

当然，这个自定义的mx-标签也可以写属性和内容，然后解析的时候做处理即可。

```html
<div mx-view="app/views/list">
    <mx-loading from="index">loading content</mx-loading>
</div>
```

```js
var combineTool = require('magix-combine');

combineTool.config({
    loaderType:'cmd', //or amd
    mxTagProcessor:function(tagInfo){
        // tagInfo.tag 获取去掉mx-的名称
        // tagInfo.attrs  获取属性
        // tagInfo.content 获取标签内容
         if(tagInfo.tag=='loading'){//获取标签名字，去掉mx-后的名字
            return '<div class="loading"><span></span><span></span><span></span></div>';
         }
        return '';//如果不能识别，则返回空字符串，删除掉这个标签
    }
});
```

**Comment by bigfengyu** [comment]
重复的代码片段为什么不直接抽象成 view 呢？

**Comment by xinglie** [comment]
@bigfengyu 这里的主要是`html`片断的重复，不适合抽离成`view`

**Comment by bigfengyu** [comment]
@xinglie 为什么？抽离成 view 会有额外开销么？我觉得那样的话可以用 scoped css ，还可以把 html 写到 .html 文件中。这样用 if 语句判断最后会不会变得特别长？

**Comment by xinglie** [comment]
@bigfengyu 

在`magix`项目中，因为只有`js`是全能的，所以`html`与`css`都是依附在`js`文件上，一个view可以没有`html`或`css`文件，但不能没有`js`文件。

实际开发中，像该示例所说的，有一些`组件`并不需要`js`文件，只需要`html`，最多再加上`css`就可以了，这种情况如果封装成`view`就显得“笨重”了。因为封装成`view`就必然有`js`文件，但这个`js`文件又没存在的必要。

所以针对这种情况，就可以使用`mx-tag`来解决复用`html`的问题

`magix-combine`提供的功能很多，同一个问题有很多种方案，我没办法确定哪个方案更优，所以都尽可能的提供多种功能。这个功能很早都有了，在项目中也少有用到，先把方案提供出来，看使用者的意见，如果某个功能用的多就重点解决它带来的问题。

if语句多的问题也好解决，只是没有人用，就没有持续跟进。

现在`magix`的组件也完善的差不多了，https://github.com/magix-components/magix-components ，我计划在下一版中把自定义标签和组件对应上，把原来如下的代码
```html
<div mx-view="app/gallery/pagination/index" view-total="200"></div>
```

换成
```html
<mx-pagination total="200" />
```
的写法。

所以接下来一段时间可能会重点完善这个功能点。

**Comment by xinglie** [comment]
@bigfengyu 

如果组件能写成`<mx-pagination />`的形式，复用代码片断也写成`<mx-snippets-loading />`的形式，对于使用者来讲，他都是拿自定义标签完成相应的功能，不用管到底是独立`view`还是只是一段`html`，同时最后产出的代码又没有冗余的`js`（对于只输出一段`html`来说），开发体验和最后的应用执行效率都会是一个好的提升吧。

当然，这只是我目前的一个想法，有待项目中实践

**Comment by xinglie** [comment]
## 支持magix-gallery
> 由于组件的完善 https://github.com/thx/magix-gallery 后续为了简化组件的调用，支持使用mx-tag的形式进行组件的调用

使用前
```html
<div mx-view="app/gallery/mx-dropdown/multiple"
    view-list="<%@list%>"
    view-text-key="text"
    view-value-key="id"
></div>
```
使用后
```html
<mx-dropdown.multiple
    list="<%@list%>"
    text-key="text"
    value-key="id" />
```

**Comment by xinglie** [comment]
## mx-tag总结
> 对应源码在：https://github.com/thx/magix-combine/blob/master/plugins/tmpl-mxtag.js
### mx-view
> 渲染一个`view`，使用方式

```html
<mx-view
    view="path/to/view"
    param1="<%@ [1,2,3]%>"/>
```
默认使用`div`渲染`path/to/view`，如果需要改变渲染标签可以使用`tag`属性，如
```html
<mx-view
    tag="ul"
    view="path/to/view"
    param1="<%@ [1,2,3]%>"/>
```

### mx-include
> 引用另外一个文件内容

```html
<mx-include path="../includes/footer.html" />
```
会使用`footer.html`的文件内容替换掉当前`mx-include`标签

### mx-name
> 该模式下有3种情况

#### 第1种情况
当`mx-name`存在`app/gallery/`文件夹下时，如`mx-dropdown`，则表示在引用组件

***注意：使用`.`表示文件夹的包含***
```html
<mx-dropdown.multiple
    list="<%@list%>" />
```
这里表示使用`app/gallery/mx-dropdown/multiple`这个组件

#### 第2种情况
当`mx-name`这个`name`是原生标签名时，如`mx-input`，则表示是对原生标签的扩充，这里目前只扩充了`boolean`属性的处理
> 对于标签的boolean属性，如<input type="radio" checked />，当要默认选中时，我们要添加checked这个属性，而如果非选中时，我们要移除这个checked属性，操作起来比较麻烦，我希望这样处理checked属性：<input type="radio" checked="true|false" /> 当checked是true时选中，false时非选中，所以为了方便这样的写法，对原生标签进行了扩充

```html
<mx-input type="radio" checked="false" />
```
上面的html片断会被编译成

```html
<input type="radio" />
```

#### 第3种情况

当不满足前2种情况时，会调用配置中的`mxTagProcessor`这个函数，供开发者更灵活的处理项目中自定义的其它mx-tag

### mx-native
> native主要处理原生标签与组件冲突的问题

如原生标签有一个`progress`，组件中也有一个`mx-progress`，如以下的代码

```html
<mx-progress  value="20" />
```
我们无法确定是使用组件还是原生标签，根据前述的规则，这种情况下会优先使用组件。如果开发者就想使用原生标签，则可以写成下面的样子

```html
<mx-native.progress  value="20" />
```

**Comment by xinglie** [comment]
完结，后续以 https://github.com/thx/magix-combine/issues/28 为准
